#!/bin/bash
echo -e "Hello, World"[D[D[D[D[D[[[C[C[C[C[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[C[C[C[C[C[C[C[C[Cecho -e "Hello, World'[D[D[D[D[D[D[D[D[D[D[D[D[[C'[C[C[C[C[C[C[C[C[C[Cecho -e 'Hello, world'
